# Generated by Django 6.0.2 on 2026-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('vacaciones', 'Vacaciones'), ('franquicia', 'Franquicia'), ('razon_particular', 'Razón Particular'), ('comision', 'Comisión')], max_length=20),
        ),
    ]
