# Generated by Django 6.0.2 on 2026-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0002_alter_record_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
