# Generated by Django 6.0.2 on 2026-02-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experimentapp', '0003_remove_agent_email_agent_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name']},
        ),
    ]
