from django.core.management.base import BaseCommand
from experimentapp.models import Agent

class Command(BaseCommand):
    help = 'Populates the database with the initial list of agents'

    def handle(self, *args, **options):
        agents_data = [
            # PLANTA 12
            ("AVALOS CLAUDIO OSCAR", "Planta 12"),
            ("BARNETCHE MARIANO", "Planta 12"),
            ("CABRAL DIEGO EDUARDO", "Planta 12"),
            ("CALDERON ALEJANDRO RAFAEL", "Planta 12"),
            ("CAMPOS ALFREDO EMILIO", "Planta 12"),
            ("CARBONEL GABRIELA ANALIA", "Planta 12"),
            ("COTO EMILIO MARTIN", "Planta 12"),
            ("DE CANDIA SEBASTIAN GASTON", "Planta 12"),
            ("ERRECART MARIA SILVIA", "Planta 12"),
            ("ESCOBAR JOSE ALFREDO", "Planta 12"),
            ("ESPINOSA GABRIEL ORLANDO", "Planta 12"),
            ("FABRIS DARIO ALEJANDRO", "Planta 12"),
            ("FERNANDEZ ALEJANDRO MIGUEL", "Planta 12"),
            ("FLORES CLAUDIA MARCELA", "Planta 12"),
            ("FONTANA NATALIA ELIZABETH", "Planta 12"),
            ("GALLEGO JAVIER ALEJANDRO", "Planta 12"),
            ("GALLUZZO ALBERTO OMAR", "Planta 12"),
            ("GIMENEZ JULIO ALBERTO", "Planta 12"),
            ("GONZALEZ GABRIELA BEATRIZ", "Planta 12"),
            ("GRASSO ADRIAN EMILIO", "Planta 12"),
            ("GUTIERREZ GERARDO ALBERTO", "Planta 12"),
            ("IÑIGUIEZ SILVIA ALEJANDRA", "Planta 12"),
            ("IRACI FRANCISCO LEONARDO", "Planta 12"),
            ("LEON JOSE LUIS", "Planta 12"),
            ("LLOPIS DANIELA NOEMI", "Planta 12"),
            ("LOSADA JORGE RICARDO", "Planta 12"),
            ("LOZA LUIS FERNANDO", "Planta 12"),
            ("MANCA JOSE ANTONIO", "Planta 12"),
            ("MARTINEZ ALBERTO CLAUDIO", "Planta 12"),
            ("MARTINEZ NATALIA KARINA", "Planta 12"),
            ("MINI MARCELO FABIAN", "Planta 12"),
            ("MIRANDA CRISTINA GABRIELA", "Planta 12"),
            ("MORENO RICARDO ALFREDO", "Planta 12"),
            ("MUÑOZ EDGARDO MARIO", "Planta 12"),
            ("NOYA SEBASTIAN ANDRES", "Planta 12"),
            ("OLIVERI GUSTAVO DANIEL", "Planta 12"),
            ("ORDOÑEZ MARCELO CLAUDIO", "Planta 12"),
            ("PADILLA MARIO GABRIEL", "Planta 12"),
            ("PARODI MARCELA SILVANA", "Planta 12"),
            ("PERAZZO GRACIELA ANDREA", "Planta 12"),
            ("PEREZ MONICA ALEJANDRA", "Planta 12"),
            ("PERRIER GUILLERMO OSCAR", "Planta 12"),
            ("REINA MARIA EMMA", "Planta 12"),
            ("REPETTO RICARDO LUIS", "Planta 12"),
            ("RODRIGUEZ MONICA LILIANA", "Planta 12"),
            ("ROJO LEONARDO MARCELO", "Planta 12"),
            ("ROSENWALD FEDERICO MARTIN", "Planta 12"),
            ("SEGRETIN LORENA MARICEL", "Planta 12"),
            ("SISTO MARIA ISABEL", "Planta 12"),
            ("SOLA VALERIA ANALIA", "Planta 12"),
            ("VALLE ARIEL MARCELO", "Planta 12"),
            ("VECCHIO MARCIO ANDRES", "Planta 12"),
            ("VERGA NATALIA SOLEDAD", "Planta 12"),
            ("VIDELA CRISTINA KARINA", "Planta 12"),
            ("VISCONTI GABRIELA ALEJANDRA", "Planta 12"),

            # PLANTA 11
            ("ALCARAZ MONICA BEATRIZ", "Planta 11"),
            ("ARANDA RAQUEL NOEMI", "Planta 11"),
            ("BLANCO ARIEL LUIS", "Planta 11"),
            ("BROGGINI MARCELA DEL LUJAN", "Planta 11"),
            ("CABANILLAS VERONICA", "Planta 11"),
            ("CAMARA CRISTIAN OSVALDO", "Planta 11"),
            ("CANO PAOLO JOSE", "Planta 11"),
            ("CASCO LUIS EDUARDO", "Planta 11"),
            ("CORIA NORMA BEATRIZ", "Planta 11"),
            ("CRISCUOLO SERGIO GUSTAVO", "Planta 11"),
            ("DIAZ ADRIAN OSCAR", "Planta 11"),
            ("FAIDUTTI EDUARDO ENRIQUE", "Planta 11"),
            ("GOMILA GUSTAVO CLAUDIO", "Planta 11"),
            ("LEDESMA ADRIANA", "Planta 11"),
            ("MALDONADO ADRIANA LUCIA", "Planta 11"),
            ("MORABITO ADRIANA BEATRIZ", "Planta 11"),
            ("MORO ALBERTO MARCELO", "Planta 11"),
            ("MURUA OSCAR DANIEL", "Planta 11"),
            ("OLMOS ANALIA ELIZABETH", "Planta 11"),
            ("ROLDAN JORGE LUIS", "Planta 11"),
            ("ROMERO ALICIA BEATRIZ", "Planta 11"),
            ("SAAVEDRA LILIANA MABEL", "Planta 11"),
            ("SANCHEZ LILIANA RAQUEL", "Planta 11"),
            ("SCRIBANO LUIS ALBERTO", "Planta 11"),
            ("SEGURA CLAUDIA", "Planta 11"),
            ("SILVA JORGE ALBERTO", "Planta 11"),
            ("SOTTO SILVIA GRACIELA", "Planta 11"),
            ("TARASCONI CARLOS ALBERTO", "Planta 11"),
            ("VEGA MARIA CRISTINA", "Planta 11"),
            ("VILLARRUEL ENRIQUE ESTEBAN", "Planta 11"),

            # PLANTA 9
            ("BASCONCELO ALFREDO", "Planta 9"),
            ("CARNERO MARCELO", "Planta 9"),
            ("CORA RUBEN", "Planta 9"),
            ("DAVERIO SILVIA BEATRIZ", "Planta 9"),
            ("GALIANO CLAUDIO", "Planta 9"),
            ("GOMEZ MARCOS ALDO", "Planta 9"),
            ("GUIL GUSTAVO ADRIAN", "Planta 9"),
            ("MATYI VALERIA ELIZABETH", "Planta 9"),
            ("MEZZAPELLE SERGIO ANTONIO", "Planta 9"),
            ("NIERE MARCELA JUDITH", "Planta 9"),
            ("PEREZ ELIZABETH BEATRIZ", "Planta 9"),
            ("QUARTINO GABRIEL", "Planta 9"),
            ("SARUBBI ALVARO", "Planta 9"),
            ("SEGUI MARCELO ALBERTO", "Planta 9"),
            ("TUDELA MARIANO ANDRES", "Planta 9"),
            ("VAZQUEZ MARCELO", "Planta 9"),

            # PLANTA 8
            ("ALFONSO ELIAS CARLOS", "Planta 8"),
            ("AMIGO GABRIEL", "Planta 8"),
            ("ARCAJO RAUL", "Planta 8"),
            ("BASSANO FABIAN", "Planta 8"),
            ("BECERRA LUIS", "Planta 8"),
            ("BERTOLI GUILLERMO", "Planta 8"),
            ("CAMPARO RICARDO", "Planta 8"),
            ("DIAZ JULIAN JORGE", "Planta 8"),
            ("DUARTE MARCELO", "Planta 8"),
            ("ESCOBAR ALBERTO", "Planta 8"),
            ("FERNANDEZ ADRIAN", "Planta 8"),
            ("GALARZA OSCAR", "Planta 8"),
            ("GARDANO PABLO EMILIO", "Planta 8"),
            ("GONZALEZ EDGARDO", "Planta 8"),
            ("LOUREIRO MARCELO", "Planta 8"),
            ("MONTENEGRO JAVIER RICARDO", "Planta 8"),
            ("MORELLI ALFONSO", "Planta 8"),
            ("MOYANO CARLOS", "Planta 8"),
            ("PINTOS MARCIAL", "Planta 8"),
            ("RAMIREZ ADOLFO RAUL", "Planta 8"),
            ("RIVADENEYRA PABLO ABRAHAM", "Planta 8"),
            ("RODRIGUEZ MARCELO GUILLERMO", "Planta 8"),
            ("SALDAÑA ADRIAN MARCELO", "Planta 8"),
            ("SCHIAVO RUBEN", "Planta 8"),
            ("VALLE ROMINA", "Planta 8"),
            ("VILLANUEVA ALEJANDRA", "Planta 8"),
            ("VILLARROEL EDGARDO", "Planta 8"),
            ("ZANIER RICARDO MARIO", "Planta 8"),

            # PLANTA 6
            ("AGUADO JULIA ANDREA", "Planta 6"),
            ("AQUINO CLAUDIO", "Planta 6"),
            ("ARGUELLO GUSTAVO", "Planta 6"),
            ("BARALE PABLO HUGO", "Planta 6"),
            ("BLANCO ELADIO", "Planta 6"),
            ("BUSTOS ENRIQUE", "Planta 6"),
            ("CALLES JORGE ALBERTO", "Planta 6"),
            ("COMITE MARIO DANIEL", "Planta 6"),
            ("CONDORI MARIO JAVIER", "Planta 6"),
            ("CUADRA GREGORIO", "Planta 6"),
            ("DA ROS RICARDO ALFREDO", "Planta 6"),
            ("DIAZ CARLOS OSCAR", "Planta 6"),
            ("EVANGELISTA GUSTAVO", "Planta 6"),
            ("FLEITAS CARLOS OSCAR", "Planta 6"),
            ("FRECCERO MIGUEL", "Planta 6"),
            ("GAMINO JUAN CARLOS", "Planta 6"),
            ("GOMEZ ADALBERTO", "Planta 6"),
            ("GONZALEZ JUAN CARLOS", "Planta 6"),
            ("GRAMAJO CARLOS ALBERTO", "Planta 6"),
            ("GUERRA GERMAN", "Planta 6"),
            ("ISER GUSTAVO", "Planta 6"),
            ("LEZCANO ALBERTO", "Planta 6"),
            ("LLAMOSAS MARCELA", "Planta 6"),
            ("LOPEZ GUSTAVO DAMIAN", "Planta 6"),
            ("MARCON CLAUDIO ALEJANDRO", "Planta 6"),
            ("MARTINEZ FRANCISCO DOMINGO", "Planta 6"),
            ("MEDINA LUIS ALBERTO", "Planta 6"),
            ("MONTES PAULA ELIZABETH", "Planta 6"),
            ("NAVAS RICARDO ALFREDO", "Planta 6"),
            ("OJEDA JOSE LUIS", "Planta 6"),
            ("PEÑA HUGO", "Planta 6"),
            ("PIRIZ ABRAHAM", "Planta 6"),
            ("PRIETO LUIS ALBERTO", "Planta 6"),
            ("PRIETO SERGIO DANIEL", "Planta 6"),
            ("REYES HECTOR MARCELO", "Planta 6"),
            ("ROMERO RAMON ALBERTO", "Planta 6"),
            ("SALCEDO PATRICIA SILVINA", "Planta 6"),
            ("SALINAS JORGE EMILIO", "Planta 6"),
            ("SANCHEZ ADRIAN ALEJANDRO", "Planta 6"),
            ("SANCHEZ GUSTAVO OSCAR", "Planta 6"),
            ("SANCHEZ HUGO GUALBERTO", "Planta 6"),
            ("SCANDURRA ALBERTO DOMINGO", "Planta 6"),
            ("SCHAAB RUBEN ERNESTO", "Planta 6"),
            ("SOSA EDUARDO", "Planta 6"),
            ("SPINAZZE DANIEL", "Planta 6"),
            ("STRATTA DANIEL ANTONIO", "Planta 6"),
            ("TEIXIDOR CARLOS ALBERTO", "Planta 6"),
            ("VAIANI SERGIO", "Planta 6"),
            ("VELAZQUEZ LUIS ESTEBAN", "Planta 6"),
            ("VERA RAFAEL", "Planta 6"),
            ("VILLALBA CARLOS", "Planta 6"),
            ("VILLARRUBIA CLAUDIO MARCELO", "Planta 6"),

            # PLANTA 1
            ("ALMIRON CARLOS ALBERTO", "Planta 1"),
        ]

        self.stdout.write(self.style.SUCCESS(f'Iniciando carga de {len(agents_data)} agentes...'))

        created_count = 0
        updated_count = 0

        for name, location in agents_data:
            agent, created = Agent.objects.get_or_create(
                name=name,
                defaults={'location': location}
            )
            if created:
                created_count += 1
            else:
                agent.location = location
                agent.save()
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(f'Carga completada: {created_count} creados, {updated_count} actualizados.'))
