from django.core.management.base import BaseCommand
from experimentapp.models import Agent

class Command(BaseCommand):
    help = 'Populates the database with the initial list of agents'

    def handle(self, *args, **options):
        # Limpiar agentes anteriores para evitar mezcla de datos
        Agent.objects.all().delete()
        
        agents_data = [
            ("Alfano, Emanuel Nicolás", "CONCESIONES - CENTRAL"),
            ("Aparicio, María Andrea", "CONCESIONES - CENTRAL"),
            ("Bendrame, María Luz", "CONCESIONES - CENTRAL"),
            ("Bendrame, Maríano Ernesto", "CONCESIONES - CENTRAL"),
            ("Benitez, María Shirley", "CONCESIONES - CENTRAL"),
            ("Castaño, Liliana Alejandra", "CONCESIONES - CENTRAL"),
            ("Castro, Liliana Esther", "CONCESIONES - CENTRAL"),
            ("Chiarella, Ruben Dario", "CONCESIONES - CENTRAL"),
            ("Cortopassi, Marcela", "CONCESIONES - CENTRAL"),
            ("De La Iglesia, Sabrina", "CONCESIONES - CENTRAL"),
            ("Fredes, Roberta Natalia", "CONCESIONES - CENTRAL"),
            ("Fuentes, Germán Ariel", "CONCESIONES - CENTRAL"),
            ("Furgiuele, Federico Martín", "CONCESIONES - CENTRAL"),
            ("García Herrera, Fernando Maríano", "CONCESIONES - CENTRAL"),
            ("García Ruíz, María Encarnación", "CONCESIONES - CENTRAL"),
            ("Gastrell, Diego Lucas", "CONCESIONES - CENTRAL"),
            ("Gastrell, Javier Alejandro", "CONCESIONES - CENTRAL"),
            ("Giacomelli, Maríano Ezequiel", "CONCESIONES - CENTRAL"),
            ("Keumurdji Rizzuti, Rolando", "CONCESIONES - CENTRAL"),
            ("Laugle, Nadia Soledad", "CONCESIONES - CENTRAL"),
            ("León, Pablo", "CONCESIONES - CENTRAL"),
            ("Libarona, Osvaldo Darío", "CONCESIONES - CENTRAL"),
            ("Lichtenwald, Jorge Maximiliano", "CONCESIONES - CENTRAL"),
            ("Lionetti, Guido Javier", "CONCESIONES - CENTRAL"),
            ("Llovet, Barbara", "CONCESIONES - CENTRAL"),
            ("Macedo, Carlos Cristian", "CONCESIONES - CENTRAL"),
            ("Machain, Alejandro", "CONCESIONES - CENTRAL"),
            ("Mallon, Jorge Gilberto", "CONCESIONES - CENTRAL"),
            ("Martin, Silvia Monica", "CONCESIONES - CENTRAL"),
            ("Mazzi, Ariel Osvaldo", "CONCESIONES - CENTRAL"),
            ("Mazzoni, Pablo Daniel", "CONCESIONES - CENTRAL"),
            ("Mera, Sergio Gabriel", "CONCESIONES - CENTRAL"),
            ("Merino, Daiana Elizabeth", "CONCESIONES - CENTRAL"),
            ("Musmanno, Diego", "CONCESIONES - CENTRAL"),
            ("Marino, Natalia", "CONCESIONES - CENTRAL"),
            ("Paladino, Damián Cristian", "CONCESIONES - CENTRAL"),
            ("Pereyra, Vanesa Liliana", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Quejillaver Boye, Ricardo", "CONCESIONES - CENTRAL"),
            ("Riveira, María Eugenia", "CONCESIONES - CENTRAL"),
            ("Rodriguez, Gisela Vanina", "CONCESIONES - CENTRAL"),
            ("Romero, Justo", "CONCESIONES - CENTRAL"),
            ("Rui Diaz, Camila Anabel", "CONCESIONES - CENTRAL"),
            ("Rui Diaz, Maríano Antonio", "CONCESIONES - CENTRAL"),
            ("Saenz, Martín Javier", "CONCESIONES - CENTRAL"),
            ("Scattini, Carlos María", "CONCESIONES - CENTRAL"),
            ("Schik, Javier Eduardo", "CONCESIONES - CENTRAL"),
            ("Segovia, María Soledad", "CONCESIONES - CENTRAL"),
            ("Trigo, Mirtha Elisa", "CONCESIONES - CENTRAL"),
            ("Vazquez, Maríano", "CONCESIONES - CENTRAL"),
            ("Zalabardo, Gabriela Silvana", "CONCESIONES - CENTRAL"),
            ("Zelaschi, Pablo", "CONCESIONES - CENTRAL"),
            ("Zanek, Pablo Agustin", "CONCESIONES - CENTRAL"),
            ("Acevedo Luque, María José De Jesús", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Maneiro, Sergio Fernando", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Romano, Gabriel Sebastian", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Rosa, Marina Fabiana", "CONCESIONES - CENTRAL"),
            ("Rosales, Pablo René", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Vilariño, Pilar", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Zabala, Luis Alberto", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Zabala, Natalia Olga", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Ahumada, Mabel Nélida", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE OBRA"),
            ("Sosa Kosir, Alejandro", "CONCESIONES - CENTRAL"),
            ("Aparicio, Santiago", "CONCESIONES - SUPERVISIÓN - ACCESO NORTE"),
            ("Celi, Brian Walter", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Celi, Yasmín Eliane", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Comerci, Fernando", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Lorenzi, Fernando Martin", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Sanchez, Sandra Silvina", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Verdun, Fernanda Gabriela", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Gomez, Bernardo Federico", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Hardouin, Daniela", "CONCESIONES - SUPERVISIÓN - TRAMO ORIENTAL"),
            ("Torres Mareco, Raúl Elias", "CONCESIONES - SUPERVISIÓN - ACCESO OESTE"),
            ("Colicelli, Alexis Ramón", "CONCESIONES - SUPERVISIÓN - TRAMO ORIENTAL"),
            ("García, Alejandro Carlos", "CONCESIONES - SUPERVISIÓN - TRAMO ORIENTAL"),
            ("Issolio, Francisco Miguel", "CONCESIONES - SUPERVISIÓN - TRAMO ORIENTAL"),
            ("Marchini, David Julio", "CV18"),
            ("Rico, Oscar Daniel", "CONCESIONES - SUPERVISIÓN - TRAMO ORIENTAL"),
            ("Santamaría, Juan Manuel", "CV18"),
            ("Urteaga, Hugo Ronald", "CV18"),
            ("Condrac, José Elías", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Fernández, Ceferino Eugenio", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Fernandez, Marcos Alberto", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Fierro, Raúl Edgardo", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Morales, Luis Orlando", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Papa, Mario Alfredo", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Salomon, Daniel Oscar", "CONCESIONES - SUPERVISIÓN - TRAMO I"),
            ("Alvarez, Santiago", "CONCESIONES - SUPERVISIÓN - TRAMO II"),
            ("Cabral, Paula Lorena", "CONCESIONES - SUPERVISIÓN - TRAMO II"),
            ("Gracioli, Pedro Martin", "CONCESIONES - SUPERVISIÓN - TRAMO CONEXIÓN"),
            ("Sciarratta, Jose German", "CONCESIONES - SUPERVISIÓN - TRAMO II"),
            ("Benitez Klaner, Ada Teresa", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Berend, Valeria Judith", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Espindola, Fabio Martín", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Peralta, Sergio Jesus", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Retamar, Darío Martiniano", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Soria, Daniel Roque Benito", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Sosa, Ruben Anibal", "CONCESIONES - SUPERVISIÓN - TRAMO III"),
            ("Bonino, Hugo Ariel", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Giribaldi, Gaston", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Peralta, Cristian Ariel", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Pisani, Diego Andres", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Tocalini, Adalberto Raul", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Tomino Wilson, Hector Antonio", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Urbizu, Carolina", "CONCESIONES - SUPERVISIÓN - TRAMO IV"),
            ("Dell´Ordine, Alicia", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Farias, Juan Manuel", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Fernandez Puga, Juan Pablo", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Gutierrez Lanöel, Emiliano Manuel", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Luna, Luis Guillermo", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Monetti, Diego Hernán", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Perez Mundo, Patricio", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Vallejos, Roberto", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Vazquez, Cristela Mariel", "CONCESIONES - SUPERVISIÓN - TRAMO IX"),
            ("Aguinaga, Juan Manuel", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Buono, Fernando Alberto", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Ereñu, María Virginia", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Faustinelli, Fabio", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Narvaez, Alejandro Fabian", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Narvaez, María Florencia", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Perretta, Lorena Veronica", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Victoria, Julio Cesar", "CONCESIONES - SUPERVISIÓN - TRAMO V"),
            ("Asenjo, Nestor Adrián", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Casadó, Gastón Emilio", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("De La Encina, Gustavo Héctor", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Del Buono, Nicolás", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Fassetta, Edgar Clemar", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Novello Castro, Guillermo Ricardo", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Oltra, Natalia Carolina", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Prato, Ulises", "CONCESIONES - SUPERVISIÓN - TRAMO VI"),
            ("Bonini, María Cruz", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Durso, Remigio", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Nieto, Diego Marcelo", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Perez, Alexis", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Speranza, Mauro Damian", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Tolosa, Eneas Yairza", "CONCESIONES - SUPERVISIÓN - TRAMO VII"),
            ("Cuadrado, Marcelo Lorenzo", "CONCESIONES - SUPERVISIÓN - TRAMO VIII"),
            ("Lamelza, Gerardo Daniel", "CONCESIONES - SUPERVISIÓN - TRAMO VIII"),
            ("Marti, Alejandro", "CONCESIONES - SUPERVISIÓN - TRAMO VIII"),
            ("Troiano, Ruben Oscar", "CONCESIONES - SUPERVISIÓN - TRAMO VIII"),
            ("Vivero, Marcelo", "CONCESIONES - SUPERVISIÓN - TRAMO VIII"),
            ("Caia, Jonatan Matías", "CONCESIONES - SUPERVISIÓN - TRAMO X"),
            ("Diaz, Ignacio Rodolfo", "CONCESIONES - SUPERVISIÓN - TRAMO X"),
            ("García, Raúl Ernesto", "CONCESIONES - SUPERVISIÓN - TRAMO X"),
            ("Martin, Alejandro Luis", "CONCESIONES - SUPERVISIÓN - TRAMO X"),
            ("Rojo, Daniel Nelson", "CONCESIONES - SUPERVISIÓN - TRAMO X"),
            ("Crivelero, Silvina Marcela.", "PLANEAMIENTO"),
            ("Mejuto, Sandra Lorena", "PLANEAMIENTO"),
            ("Hernando, Marie Noel", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Niz, Hugo Leonardo", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Dulout, Mariana Hebe", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Galmarini, Ana Julia", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Keumurdji, Paula", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Pereyra, Juan Facundo", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Yunis, Sabina", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Vargas, Vanesa Ivana", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS SOCIOAMBIENTALES"),
            ("Cerzosimo, Damián", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Fraschetti, Martín Andrés", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Gonzalez Rillo, María Julia", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Lariño, Matías Fernando", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Polo, Raúl Javier", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Suarez, Graciela Adriana", "PLANEAMIENTO - SUBGERENCIA DE ESTUDIOS ECONÓMICOS"),
            ("Mazzitelli, Patricia Adriana", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Monzon, Diana María", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Jauregui Lorda, Mario", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Margolin, Claudio Armando", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Garay, Daniela Carolina", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Collizzolli, Camila", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Vimini, Emilio Fabián", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("García, Augusto Nahuel", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Garofalo, Facundo Germán", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Mendez Marecos, Rut Daiana", "PLANEAMIENTO - PROGRAMAS Y PRESTAMOS EXTERNOS"),
            ("Barber, Agustín", "PLANEAMIENTO - DEMANDA"),
            ("Cutrone, María Clara", "PLANEAMIENTO - DEMANDA"),
            ("Di Rosso, Alejandro Francisco", "PLANEAMIENTO - DEMANDA"),
            ("Gonzalez, Rogelio Diego", "PLANEAMIENTO - DEMANDA"),
            ("Mancini, Carlos Alberto", "PLANEAMIENTO - DEMANDA"),
            ("Vazquez, Diego Aníbal", "PLANEAMIENTO - DEMANDA"),
            ("Vela Diaz, Patricia Gianina", "PLANEAMIENTO - DEMANDA"),
            ("Pendones Fernandez, Emmanuel", "PLANEAMIENTO - DEMANDA"),
            ("Alvarez, Julián Alejandro", "PLANEAMIENTO - DEMANDA"),
            ("Maisani, Alan Demian", "PLANEAMIENTO - DEMANDA"),
        ]

        self.stdout.write(self.style.SUCCESS(f'Iniciando carga de {len(agents_data)} agentes...'))

        created_count = 0
        updated_count = 0

        for name, location in agents_data:
            agent, created = Agent.objects.get_or_create(
                name=name,
                defaults={'location': location}
            )
            if created:
                created_count += 1
            else:
                agent.location = location
                agent.save()
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(f'Carga completada: {created_count} creados, {updated_count} actualizados.'))
